// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using YPP.MH.Shared.BaseEntity;

namespace YPP.MH.DataAccessLayer.Models
{
    [Table("User")]
    public partial class User : BaseEntity
    {
        [Key]
        public int Id { get; set; }

        [StringLength(255)]
        public string? FullName { get; set; }

        [StringLength(255)]
        public string? Email { get; set; }

        [StringLength(255)]
        public string? Password { get; set; }
        public string? Role { get; set; } = null!;
        public string Gender { get; set; } = GenderType.Unknown.ToString();

        [StringLength(255)]
        public string? ProfileImg { get; set; } = string.Empty;
        public string? RememberMeToken { get; set; } = string.Empty;
        public DateTime? JoinedOn { get; set; } = null;
        public string? Location { get; set; } = string.Empty;
        public bool? EmailConfirmed { get; set; } = false;
        public string? ConfirmationToken { get; set; } = string.Empty;
        public string? Company { get; set; } = string.Empty;
        public int? MentoringTopic { get; set; } = null;
        public string? JobTitle { get; set; } = string.Empty;
        public virtual ICollection<SpaceMember> Spaces { get; set; } = new HashSet<SpaceMember>();
        public string? PasswordResetToken { get; set; }
        public DateTime? PasswordResetTokenExpiration { get; set; }

    }

}
